# Generated by Django 3.1.6 on 2021-04-15 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fundName',
            new_name='Fund',
        ),
        migrations.RenameModel(
            old_name='getdatePrice',
            new_name='Price',
        ),
        migrations.RenameModel(
            old_name='stockName',
            new_name='Stock',
        ),
    ]
