# Generated by Django 3.1.6 on 2021-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210415_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='EPS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='Yield',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='marketCap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='pEratio',
            field=models.FloatField(default=0.0),
        ),
    ]
