# Generated by Django 3.1.6 on 2021-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210526_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='EPS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fund',
            name='Volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fund',
            name='Yield',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fund',
            name='netAssets',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fund',
            name='pEratio',
            field=models.FloatField(default=0.0),
        ),
    ]
