# Generated by Django 3.1.6 on 2021-05-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210530_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='userName',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
