# Generated by Django 3.1.6 on 2021-06-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20210530_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='numShares',
        ),
        migrations.AddField(
            model_name='stock',
            name='numShares',
            field=models.IntegerField(default=0.0),
        ),
    ]
